PCA:
  type: sklearn.decomposition.PCA
  init_args:
    n_components: 41

VotingClassifier:
  type: sklearn.ensemble.VotingClassifier
  init_args:
    flatten_transform: False
  estimators:
    - LinearDiscriminantAnalysis
    - RandomForestClassifier
    - SVC

LinearDiscriminantAnalysis:
  type: sklearn.discriminant_analysis.LinearDiscriminantAnalysis
  init_args:
    solver: svd

RandomForestClassifier:
  type: sklearn.ensemble.RandomForestClassifier
  init_args:
    n_estimators: 500
    max_leaf_nodes: 2
    random_state: 6020

SVC:
  type: sklearn.svm.SVC
  init_args:
    kernel: linear
    probability: True
    random_state: 6020